name: Backport Production to Partner

on:
  push:
    branches:
      - feature/backport-bot

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create temporary branch from Production to backport changes to Partner
        uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: backport-production-to-partner

      - name: Update temporary branch with latest changes on Production
        uses: connor-baer/action-sync-branch@main
        with:
          branch: backport-production-to-partner
          force: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Backport
        id: backport
        uses: cristiammercado/backport-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-from-branch: mdemblani:backport-production-to-partner
          pr-to-branch: partner
          pr-title: "[Backport PR] From Production to Partner"
          pr-body: "
            [![Backport Production to Partner](https://github.com/mdemblani/github-actions-test/actions/workflows/backport-production-to-partner.yml/badge.svg)](https://github.com/mdemblani/github-actions-test/actions/workflows/backport-production-to-partner.yml)

            Merge changes from Production to Partner
          "
          pr-fail-if-exists: false
          pr-update-if-exists: true

      - name: Output from action
        run: |
          echo "PR Number: ${{ steps.backport.outputs.pr-number }}"
          echo "PR URL: ${{ steps.backport.outputs.pr-url }}"
          echo "PR SHA: ${{ steps.backport.outputs.pr-sha }}"
