name: Open PR from Release Branch to Master

on:
  push:
    branches:
      - release/**

env:
  master_branch: master

jobs:
  open-pr-from-release-branch:
    name: "Open a PR from `${{ github.ref_name }}`"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Open PR
        id: open-pr
        uses: cristiammercado/cm-backport-pr@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-from-branch: mdemblani:${{ github.ref_name }}
          pr-to-branch: master
          pr-title: "[Release PR] From Release `${{ github.ref_name }}` to `${{ env.master_branch }}`"
          pr-body: "
            [![Open a PR from `${{ github.ref_name }}`](https://github.com/mdemblani/github-actions-test/actions/workflows/open_pr_from_release_branch.yml/badge.svg)](https://github.com/mdemblani/github-actions-test/actions/workflows/open_pr_from_release_branch.yml)
            \n\n
            Merge changes from Release **`${{ github.ref_name }}`** to `${{ env.master_branch }}`
          "
          pr-fail-if-exists: false
          pr-update-if-exists: true

      - name: Output from action
        run: |
          echo "PR URL: ${{ steps.open-pr.outputs.pr-url }}"
